<?xml version="1.0"?>
<package format="2">
  <name>mine_slam_bringup</name>
  <version>0.1.0</version>
  <description>Bringup and data capture launch files for Tunnel-LIO.</description>

  <maintainer email="bai@example.com">bai</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>lio_local_odometry</build_depend>
  <build_depend>message_generation</build_depend>
  <build_depend>roscpp</build_depend>
  <build_depend>roslaunch</build_depend>
  <build_depend>std_msgs</build_depend>

  <exec_depend>imu_modbus_driver</exec_depend>
  <exec_depend>machine_state_manager</exec_depend>
  <exec_depend>mapping_control</exec_depend>
  <exec_depend>mine_slam_calibration</exec_depend>
  <exec_depend>lidar_fusion</exec_depend>
  <exec_depend>lidar_pointcloud</exec_depend>
  <exec_depend>lio_local_odometry</exec_depend>
  <exec_depend>lio_preprocess</exec_depend>
  <exec_depend>lio_session_manager</exec_depend>
  <exec_depend>lio_state_estimator</exec_depend>
  <exec_depend>lio_time_manager</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>timoo_pointcloud</exec_depend>
  <exec_depend>rosbag</exec_depend>
  <exec_depend>message_runtime</exec_depend>
  <exec_depend>roscpp</exec_depend>
  <exec_depend>roslaunch</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>section_manager</exec_depend>
  <exec_depend>slam_backend_manager</exec_depend>
  <exec_depend>tca_manager</exec_depend>
</package>
